apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base-defaultconfig

patchesStrategicMerge:
- replicas-1.yaml
- wsrep-off.yaml

configMapGenerator:
- name: conf-d
  behavior: merge
  files:
  - galera.cnf
