apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  template:
    spec:
      containers:
      - name: mariadb
        env:
        - name: WSREP_CLUSTER_ADDRESS
          value: "gcomm://mariadb-0.mariadb"
