# Used with `getent hosts` to check how many pods that are ready
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-ready
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "false"
spec:
  publishNotReadyAddresses: false
  clusterIP: None
  selector:
    app: mariadb
