kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-data
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: pd-ssd
  replication-type: regional-pd
  zones: europe-west1-c, europe-west1-d
