---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: mysql
spec:
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: mysql-data
      resources:
        requests:
          storage: 1Gi
