apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: analytics

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: ystack-mariadb-galera
  spec:
    template:
      spec:
        containers:
        - name: "mariadb-galera"
          env:
          - name: MARIADB_GALERA_CLUSTER_ADDRESS
            value: "gcomm://ystack-mariadb-galera-headless.analytics.svc.cluster.local"
