# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mariadb-service.yaml
- mariadb-ready-service.yaml
- mysql-service.yaml
- mariadb-statefulset.yaml

images:
- name: mariadb
  newTag: 10.11.8-jammy@sha256:b4fef57eee430a8f78da9850264dfeebdbbac197122be85d746041aee35b2f2d
- name: prom/mysqld-exporter
  newTag: v0.14.0@sha256:eb6fe170738bf9181c51f5bc89f93adb26672ec49ffdcb22f55c24834003b45d
