# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mariadb-service.yaml
- mariadb-ready-service.yaml
- mysql-service.yaml
- mariadb-statefulset.yaml

images:
- name: mariadb
  newName: ghcr.io/yolean/mariadb
  newTag: 10.11.19-jammy@sha256:7f22313fc130a377a44999965bcb0a08dd5b21e8502824c1b864f792f9bc66ab
- name: prom/mysqld-exporter
  newName: ghcr.io/yolean/mysqld-exporter
  newTag: v0.20.0@sha256:abed8dac117b4ae5b70757f988e44795935b9a72c3b58d720c67ba688f8cb79e
