# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mariadb-service.yaml
- mariadb-ready-service.yaml
- mysql-service.yaml
- mariadb-statefulset.yaml

images:
- name: mariadb
  newName: ghcr.io/yolean/mariadb
  newTag: 10.11.13-jammy@sha256:e725b24af143c6b30e78eab99441e4cabac7494a69186effc2f506ea85401e2a
- name: prom/mysqld-exporter
  newName: ghcr.io/yolean/mysqld-exporter
  newTag: v0.14.0@sha256:eb6fe170738bf9181c51f5bc89f93adb26672ec49ffdcb22f55c24834003b45d
